[program:enbandeja_editorial_published]
command=php /var/www/service/bin/console messenger:consume editorial_published --queues=queue::event::editorial::published --time-limit=3600
user=www-data
numprocs=1
startsecs=0
autostart=true
autorestart=true
startretries=1
process_name=%(program_name)s_%(process_num)02d

[program:enbandeja_send_campaign]
command=php /var/www/service/bin/console messenger:consume send_campaign --queues=queue::command::send_campaign --time-limit=3600
user=www-data
numprocs=1
startsecs=0
autostart=true
autorestart=true
startretries=1
process_name=%(program_name)s_%(process_num)02d
